<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "accounting_system"
 *
 * Auto generated by Extension Builder 2018-03-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Accounting System',
    'description' => 'This is an extention for basic accounting needs',
    'category' => 'plugin',
    'author' => 'Fiacre Sankara',
    'author_email' => 'fiacre.sankara@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
